name: stop_vconf

on:
  push:
    branches: [ "main1" ]
    
jobs:    
  terraform_destroy:      
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1
        

    - name: terraform init
      run: terraform init

    - name: terraform destroy
      run: terraform destroy -auto-approve
      
